name: Build iOS Archive

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  archive:
    runs-on: macos-latest
    env:
      APPLE_ID:       ${{ secrets.APPLE_ID }}
      APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
      APPLE_TEAM_ID:  ${{ secrets.APPLE_TEAM_ID }}
      APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
      P12_BASE64:     ${{ secrets.P12_BASE64 }}
      P12_PASSWORD:   ${{ secrets.P12_PASSWORD }}
      MOBILEPROVISION_BASE64: ${{ secrets.MOBILEPROVISION_BASE64 }}

    steps:
      - uses: actions/checkout@v3

      - name: Decode & install signing assets
        run: |
          echo "$P12_BASE64" | base64 --decode > dist.p12
          security import dist.p12 \
            -k "$HOME/Library/Keychains/login.keychain-db" \
            -P "$P12_PASSWORD" -T /usr/bin/codesign
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          echo "$MOBILEPROVISION_BASE64" | base64 --decode \
            > "$HOME/Library/MobileDevice/Provisioning Profiles/kalimba.mobileprovision"

      - name: Unzip source
        run: |
          unzip kalimba-app-fresh-source.zip -d src

      - name: Archive with xcodebuild
        run: |
          cd src/ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $PWD/build/App.xcarchive \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=$APPLE_TEAM_ID \
            PRODUCT_BUNDLE_IDENTIFIER=$APP_IDENTIFIER \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="Kalimba Receptionist App" \
            archive

      - name: Export IPA
        run: |
          cd src/ios/App
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kalimba.ipa
          path: src/ios/App/build/*.ipa
